DROP TABLE IF EXISTS tb_merchant;
CREATE TABLE `tb_merchant` (
  `merchant_id` bigint NOT NULL AUTO_INCREMENT COMMENT '商户ID',
  `tenant_id` varchar(128) NOT NULL COMMENT '租户ID',
  `merchant_code` varchar(64) NOT NULL COMMENT '商户编码',
  `merchant_name` varchar(255) NOT NULL COMMENT '商户名称',
  `merchant_type` varchar(20) NOT NULL COMMENT '商户类型 (PERSONAL:个人商户, INDIVIDUAL:个体工商户, ENTERPRISE:企业商户)',
  `status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '商户状态 (PENDING:待审核, ACTIVE:激活, REPOSE:休眠, DISABLED:禁用, FROZEN:冻结)',
  `level` varchar(20) NOT NULL DEFAULT 'NORMAL' COMMENT '商户等级 (NORMAL:普通商户, SILVER:银牌商户, GOLD:金牌商户, DIAMOND:钻石商户)',
  `legal_person` varchar(50) DEFAULT NULL COMMENT '法人姓名',
  `legal_person_id_number` varchar(18) DEFAULT NULL COMMENT '法人身份证号',
  `legal_person_id_front` varchar(255) DEFAULT NULL COMMENT '法人身份证国徽面照片',
  `legal_person_id_back` varchar(255) DEFAULT NULL COMMENT '法人身份证人像面照片',
  `business_license` varchar(255) DEFAULT NULL COMMENT '营业执照',
  `contact_person` varchar(50) DEFAULT NULL COMMENT '联系人',
  `contact_phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `contact_email` varchar(100) DEFAULT NULL COMMENT '联系邮箱',
  `precise_location` varchar(100) DEFAULT NULL COMMENT '经纬度',
  `address` varchar(500) DEFAULT NULL COMMENT '商户地址',
  `outer_picture` varchar(255) DEFAULT NULL COMMENT '门头图片',
  `inner_picture` varchar(255) DEFAULT NULL COMMENT '内部图片',
  `logo` varchar(255) DEFAULT NULL COMMENT '商户logo',
  `description` text COMMENT '商户描述',
  `deposit_amount` decimal(10,2) DEFAULT NULL COMMENT '保证金',
  `settlement_cycle` int DEFAULT NULL COMMENT '结算周期(天)',
  `certified` tinyint(1) NOT NULL DEFAULT '0' COMMENT '认证状态 (0:未认证, 1:已认证)',
  `certified_time` datetime DEFAULT NULL COMMENT '认证时间',
  `join_time` datetime DEFAULT NULL COMMENT '入驻时间',
  `create_dept` bigint NULL COMMENT '创建部门',
  `create_by` bigint NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint NULL COMMENT '修改人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`merchant_id`),
  UNIQUE KEY `uk_merchant_code` (`merchant_code`),
  KEY `idx_tenant_id` (`tenant_id`),
  KEY `idx_merchant_name` (`merchant_name`),
  KEY `idx_status` (`status`),
  KEY `idx_certified` (`certified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商户表';