DROP TABLE IF EXISTS `tb_spu`;
CREATE TABLE `tb_spu` (
  `id` bigint NOT NULL COMMENT '主键',
  `sn` varchar(60) DEFAULT NULL COMMENT '货号',
  `name` varchar(100) DEFAULT NULL COMMENT 'SPU名',
  `caption` varchar(100) DEFAULT NULL COMMENT '副标题',
  `brand_id` int DEFAULT NULL COMMENT '品牌ID',
  `category1_id` int DEFAULT NULL COMMENT '一级分类',
  `category2_id` int DEFAULT NULL COMMENT '二级分类',
  `category3_id` int DEFAULT NULL COMMENT '三级分类',
  `template_id` int DEFAULT NULL COMMENT '模板ID',
  `freight_id` varchar(255) DEFAULT NULL COMMENT '运费模板id',
  `freight_type` char(1) DEFAULT '1' COMMENT '配送方式：0无需配送 1需要配送',
  `image` varchar(100) DEFAULT NULL COMMENT '图片',
  `images` varchar(1000) DEFAULT NULL COMMENT '图片列表',
  `video` varchar(255) DEFAULT NULL COMMENT '视频',
  `sale_service` varchar(50) DEFAULT NULL COMMENT '售后服务',
  `introduction` text COMMENT '介绍',
  `spec_items` varchar(3000) DEFAULT NULL COMMENT '规格列表',
  `para_items` varchar(3000) DEFAULT NULL COMMENT '参数列表',
  `sale_num` int DEFAULT '0' COMMENT '销量',
  `comment_num` int DEFAULT '0' COMMENT '评论数',
  `type` varchar(128) DEFAULT NULL COMMENT '商品类型',
  `commition` decimal(10,2) DEFAULT '0.00' COMMENT '佣金',
  `cart` char(1) DEFAULT '1' COMMENT '商品能否加入购物车 0否 1是 默认1',
  `stock_unit` varchar(16) DEFAULT NULL COMMENT '库存单位',
  `marketable_mode` char(1) DEFAULT NULL COMMENT '上架类型：0立即上架 1暂不上架 2定时上架',
  `marketable_time` datetime DEFAULT NULL COMMENT '定时上架时间',
  `unmarketable_time` datetime DEFAULT NULL COMMENT '定时下架',
  `is_marketable` char(1) DEFAULT '0' COMMENT '是否上架,0已下架，1已上架',
  `is_enable_spec` char(1) DEFAULT '1' COMMENT '是否启用规格',
  `is_delete` char(1) DEFAULT '0' COMMENT '是否删除,0:未删除，1：已删除',
  `status` char(1) DEFAULT '0' COMMENT '审核状态，0：未审核，1：已审核，2：审核不通过',
  `merchant_id` bigint NOT NULL COMMENT '商户ID',
  `tenant_id` varchar(128) NOT NULL COMMENT '租户ID',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_merchant_id` (`merchant_id`),
  KEY `idx_category_hierarchy` (`category1_id`,`category2_id`,`category3_id`),
  KEY `idx_category2_id` (`category2_id`),
  KEY `idx_category3_id` (`category3_id`),
  KEY `idx_status_marketable` (`status`,`is_marketable`),
  KEY `idx_brand_category` (`brand_id`,`category1_id`),
  KEY `idx_sale_comment` (`sale_num`,`comment_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='商品spu'