DROP TABLE IF EXISTS `tb_spu`;
CREATE TABLE `tb_spu` (
  `id` bigint NOT NULL COMMENT '主键',
  `sn` varchar(60) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '货号',
  `name` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'SPU名',
  `caption` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '副标题',
  `brand_id` int DEFAULT NULL COMMENT '品牌ID',
  `category1_id` int DEFAULT NULL COMMENT '一级分类',
  `category2_id` int DEFAULT NULL COMMENT '二级分类',
  `category3_id` int DEFAULT NULL COMMENT '三级分类',
  `template_id` int DEFAULT NULL COMMENT '模板ID',
  `freight_id` int DEFAULT NULL COMMENT '运费模板id',
  `image` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '图片',
  `images` varchar(1000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '图片列表',
  `sale_service` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '售后服务',
  `introduction` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci COMMENT '介绍',
  `spec_items` varchar(3000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '规格列表',
  `para_items` varchar(3000) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '参数列表',
  `sale_num` int DEFAULT '0' COMMENT '销量',
  `comment_num` int DEFAULT '0' COMMENT '评论数',
  `is_marketable` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '0' COMMENT '是否上架,0已下架，1已上架',
  `is_enable_spec` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '1' COMMENT '是否启用规格',
  `is_delete` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '0' COMMENT '是否删除,0:未删除，1：已删除',
  `status` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '0' COMMENT '审核状态，0：未审核，1：已审核，2：审核不通过',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC COMMENT '商品spu';