-- 快递订单表
DROP TABLE IF EXISTS `tb_express_order`;
CREATE TABLE `tb_express_order` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `merchant_id` bigint DEFAULT NULL COMMENT '商家ID',
    `express_no` varchar(100) DEFAULT NULL COMMENT '快递单号',
    `express_code` varchar(50) DEFAULT NULL COMMENT '快递公司编码',
    `express_name` varchar(100) DEFAULT NULL COMMENT '快递公司名称',
    `sender_name` varchar(100) DEFAULT NULL COMMENT '发货人姓名',
    `sender_phone` varchar(20) DEFAULT NULL COMMENT '发货人电话',
    `sender_province` varchar(50) DEFAULT NULL COMMENT '发货人省份',
    `sender_city` varchar(50) DEFAULT NULL COMMENT '发货人城市',
    `sender_area` varchar(50) DEFAULT NULL COMMENT '发货人区域',
    `sender_address` varchar(200) DEFAULT NULL COMMENT '发货人详细地址',
    `receiver_name` varchar(100) DEFAULT NULL COMMENT '收货人姓名',
    `receiver_phone` varchar(20) DEFAULT NULL COMMENT '收货人电话',
    `receiver_province` varchar(50) DEFAULT NULL COMMENT '收货人省份',
    `receiver_city` varchar(50) DEFAULT NULL COMMENT '收货人城市',
    `receiver_area` varchar(50) DEFAULT NULL COMMENT '收货人区域',
    `receiver_address` varchar(200) DEFAULT NULL COMMENT '收货人详细地址',
    `goods_name` varchar(200) DEFAULT NULL COMMENT '物品名称',
    `goods_count` int DEFAULT '1' COMMENT '物品数量',
    `goods_weight` decimal(10,2) DEFAULT NULL COMMENT '物品重量(kg)',
    `goods_volume` decimal(10,2) DEFAULT NULL COMMENT '物品体积',
    `order_amount` decimal(10,2) DEFAULT NULL COMMENT '订单金额',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `order_status` varchar(20) DEFAULT 'pending' COMMENT '订单状态：pending-待揽收, shipping-运输中, delivered-已签收, refused-已拒收, abnormal-异常',
    `order_time` datetime DEFAULT NULL COMMENT '下单时间',
    `sign_time` datetime DEFAULT NULL COMMENT '签收时间',
    `ext_data` json DEFAULT NULL COMMENT '扩展字段JSON',
    `tenant_id`            VARCHAR(64)     DEFAULT NULL               COMMENT '租户ID',
    `create_dept`          BIGINT(20)      DEFAULT NULL               COMMENT '创建部门',
    `create_by`            BIGINT(20)      DEFAULT NULL               COMMENT '创建者',
    `create_time`          DATETIME                                   COMMENT '创建时间',
    `update_by`            BIGINT(20)      DEFAULT NULL               COMMENT '更新者',
    `update_time`          DATETIME                                   COMMENT '更新时间',
    `del_flag` char(1) DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_express_no` (`express_no`),
    KEY `idx_tenant_id` (`tenant_id`),
    KEY `idx_merchant_id` (`merchant_id`),
    KEY `idx_express_code` (`express_code`),
    KEY `idx_order_status` (`order_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='快递订单表';
